### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rapha8l** [storyfeet/gob_sh#1]
Hi,
Can you provide some configuration examples or documentation ?

thanks

**Comment by storyfeet** [comment]
It's barely useable at this stage. I've currently fighting with some massive Async changes, I'm not sure were a good idea.  But in $HOME/.config/ru_shell/init.rush  add the line "let RU_PROMPT=r#"$PWD>>"#

And you should get something like a prompt. Config is only a file of shell commands.

**Comment by rapha8l** [comment]
thanks !
