### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by rapha8l** [storyfeet/gob_sh#2]
Hi,

I remember that you told me it's not ready and not for everyone by now :)
Though I tried to build it and got
```
error: failed to get `str_tools` as a dependency of package `ru_history v0.1.0 (/data/1/git-divers/shell-home/ru_history)`
    ... which is depended on by `ru_shell v0.1.1 (/data/1/git-divers/shell-home/gob_sh)`

Caused by:
  failed to load source for dependency `str_tools`

Caused by:
  Unable to update /data/1/git-divers/mlibs/str_tools

Caused by:
  failed to read `/data/1/git-divers/mlibs/str_tools/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Feel free to close this issue, if you don't want to bother for the moment :)

Have a nice day

Raphael

**Comment by storyfeet** [comment]
Hi, thanks for the interest.
The program is in a much better state right now, and actually quite pleasant to use.

There are several repos it needs to work, which makes the build a bit of a pain
The plan is to make them all available on crates, I will try work on that this afternoon, so that there is a live version hopefully ready by this evening, I'll post here when it's done.

**Comment by storyfeet** [comment]
Alright, I believe it should work now.  All links are now cargo links instead of local ones.
Let me know if you have any trouble running it, and I'll see what I can do.

Also the readme is much more helpful

**Comment by rapha8l** [comment]
Thanks a lot
Indeed, crates and doc are very helpful
Though I get :

```
   Compiling ru_shell v0.1.2 (/media/sd/trsh/shell-home/gob_sh)
error[E0658]: binding by-move and by-ref in the same pattern is unstable
  --> src/data.rs:58:40
   |
58 |             (Data::List(a), Data::List(b)) => a.extend(b),
   |                         -              ^ by-move pattern here
   |                         |
   |                         by-ref pattern here
   |
   = note: see issue #68354 <https://github.com/rust-lang/rust/issues/68354> for more information

error[E0658]: binding by-move and by-ref in the same pattern is unstable
  --> src/data.rs:59:29
   |
59 |             (Data::List(a), b) => a.push(b),
   |                         -   ^ by-move pattern here
   |                         |
   |                         by-ref pattern here
   |
   = note: see issue #68354 <https://github.com/rust-lang/rust/issues/68354> for more information

error[E0658]: binding by-move and by-ref in the same pattern is unstable
  --> src/data.rs:60:28
   |
60 |             (Data::Str(a), b) => a.push_str(&b.to_string()),
   |                        -   ^ by-move pattern here
   |                        |
   |                        by-ref pattern here
   |
   = note: see issue #68354 <https://github.com/rust-lang/rust/issues/68354> for more information

error[E0658]: binding by-move and by-ref in the same pattern is unstable
  --> src/data.rs:61:38
   |
61 |             (Data::Map(a), Data::Map(b)) => a.extend(b),
   |                        -             ^ by-move pattern here
   |                        |
   |                        by-ref pattern here
   |
   = note: see issue #68354 <https://github.com/rust-lang/rust/issues/68354> for more information

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `ru_shell`
```
Thanks

**Comment by storyfeet** [comment]
Have you done a "rustup update" recently?
That might solve your problem.

It's saying a feature is unstable, and I'm using stable rust to compile on my machine.

**Comment by rapha8l** [comment]
I'm using Void linux rust which is rustc 1.48.0

**Comment by storyfeet** [comment]
Ah, the current staple version is 1.52.1 (quick google. Not at my computer)  

It's common for linux distros to be behind on this stuff.

It maybe worth uninstalling the distro based version and using rustup instead. It's pretty awesome for keeping you up to date.  you can try out the nightly and beta releases with it too.   

https://rustup.rs

**Comment by rapha8l** [comment]
Thanks
I'll read a bit, and I'll tell you

**Comment by rapha8l** [comment]
It worked with rustup
Thanks !
